name: "analytics_dbt"
version: "1.0.0"
config-version: 2

profile: "analytics_dbt"

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  analytics_dbt:
    +materialized: view
